// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: grpc/node/proto/node.proto

package node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ForceLogout 请求结构
type ForceLogoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName string `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *ForceLogoutRequest) Reset() {
	*x = ForceLogoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_node_proto_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForceLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceLogoutRequest) ProtoMessage() {}

func (x *ForceLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_node_proto_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceLogoutRequest.ProtoReflect.Descriptor instead.
func (*ForceLogoutRequest) Descriptor() ([]byte, []int) {
	return file_grpc_node_proto_node_proto_rawDescGZIP(), []int{0}
}

func (x *ForceLogoutRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ForceLogoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ForceLogout 响应结构
type ForceLogoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ForceLogoutResponse) Reset() {
	*x = ForceLogoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_node_proto_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForceLogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceLogoutResponse) ProtoMessage() {}

func (x *ForceLogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_node_proto_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceLogoutResponse.ProtoReflect.Descriptor instead.
func (*ForceLogoutResponse) Descriptor() ([]byte, []int) {
	return file_grpc_node_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *ForceLogoutResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ForceLogoutResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// SendMessage 请求结构
type SendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromNodeName string                      `protobuf:"bytes,1,opt,name=fromNodeName,proto3" json:"fromNodeName,omitempty"`
	FromNodeAddr string                      `protobuf:"bytes,2,opt,name=fromNodeAddr,proto3" json:"fromNodeAddr,omitempty"`
	Message      *SendMessageRequest_Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_node_proto_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_node_proto_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_grpc_node_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetFromNodeName() string {
	if x != nil {
		return x.FromNodeName
	}
	return ""
}

func (x *SendMessageRequest) GetFromNodeAddr() string {
	if x != nil {
		return x.FromNodeAddr
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() *SendMessageRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// SendMessage 响应结构
type SendMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_node_proto_node_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_node_proto_node_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_grpc_node_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SendMessageResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 与IM系统中Message对应的结构体 这里当作grpc发送消息的参数
type SendMessageRequest_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId       string `protobuf:"bytes,1,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	MsgType     int32  `protobuf:"varint,2,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	Data        string `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	FromUid     string `protobuf:"bytes,4,opt,name=FromUid,proto3" json:"FromUid,omitempty"`
	ToUid       string `protobuf:"bytes,5,opt,name=ToUid,proto3" json:"ToUid,omitempty"`
	CreateAt    int64  `protobuf:"varint,6,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	IsRead      int32  `protobuf:"varint,7,opt,name=IsRead,proto3" json:"IsRead,omitempty"`
	ReadAt      int64  `protobuf:"varint,8,opt,name=ReadAt,proto3" json:"ReadAt,omitempty"`
	IsRevoke    int32  `protobuf:"varint,9,opt,name=IsRevoke,proto3" json:"IsRevoke,omitempty"`
	RevokeAt    int64  `protobuf:"varint,10,opt,name=RevokeAt,proto3" json:"RevokeAt,omitempty"`
	ContentType int32  `protobuf:"varint,11,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
}

func (x *SendMessageRequest_Message) Reset() {
	*x = SendMessageRequest_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_node_proto_node_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageRequest_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest_Message) ProtoMessage() {}

func (x *SendMessageRequest_Message) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_node_proto_node_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest_Message.ProtoReflect.Descriptor instead.
func (*SendMessageRequest_Message) Descriptor() ([]byte, []int) {
	return file_grpc_node_proto_node_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SendMessageRequest_Message) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendMessageRequest_Message) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *SendMessageRequest_Message) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SendMessageRequest_Message) GetFromUid() string {
	if x != nil {
		return x.FromUid
	}
	return ""
}

func (x *SendMessageRequest_Message) GetToUid() string {
	if x != nil {
		return x.ToUid
	}
	return ""
}

func (x *SendMessageRequest_Message) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *SendMessageRequest_Message) GetIsRead() int32 {
	if x != nil {
		return x.IsRead
	}
	return 0
}

func (x *SendMessageRequest_Message) GetReadAt() int64 {
	if x != nil {
		return x.ReadAt
	}
	return 0
}

func (x *SendMessageRequest_Message) GetIsRevoke() int32 {
	if x != nil {
		return x.IsRevoke
	}
	return 0
}

func (x *SendMessageRequest_Message) GetRevokeAt() int64 {
	if x != nil {
		return x.RevokeAt
	}
	return 0
}

func (x *SendMessageRequest_Message) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

var File_grpc_node_proto_node_proto protoreflect.FileDescriptor

var file_grpc_node_proto_node_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x22, 0x48, 0x0a, 0x12, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x6f, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x13,
	0x46, 0x6f, 0x72, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xbe, 0x03, 0x0a, 0x12, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d,
	0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x3a, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0xa3, 0x02, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x6f, 0x55, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x6f, 0x55, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x64,
	0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x65, 0x61, 0x64, 0x41, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x49, 0x73, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x41, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3b, 0x0a, 0x13, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x92, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x44, 0x0a, 0x0b, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12,
	0x18, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05,
	0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_node_proto_node_proto_rawDescOnce sync.Once
	file_grpc_node_proto_node_proto_rawDescData = file_grpc_node_proto_node_proto_rawDesc
)

func file_grpc_node_proto_node_proto_rawDescGZIP() []byte {
	file_grpc_node_proto_node_proto_rawDescOnce.Do(func() {
		file_grpc_node_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_node_proto_node_proto_rawDescData)
	})
	return file_grpc_node_proto_node_proto_rawDescData
}

var file_grpc_node_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_node_proto_node_proto_goTypes = []interface{}{
	(*ForceLogoutRequest)(nil),         // 0: node.ForceLogoutRequest
	(*ForceLogoutResponse)(nil),        // 1: node.ForceLogoutResponse
	(*SendMessageRequest)(nil),         // 2: node.SendMessageRequest
	(*SendMessageResponse)(nil),        // 3: node.SendMessageResponse
	(*SendMessageRequest_Message)(nil), // 4: node.SendMessageRequest.Message
}
var file_grpc_node_proto_node_proto_depIdxs = []int32{
	4, // 0: node.SendMessageRequest.message:type_name -> node.SendMessageRequest.Message
	0, // 1: node.Node.ForceLogout:input_type -> node.ForceLogoutRequest
	2, // 2: node.Node.SendMessage:input_type -> node.SendMessageRequest
	1, // 3: node.Node.ForceLogout:output_type -> node.ForceLogoutResponse
	3, // 4: node.Node.SendMessage:output_type -> node.SendMessageResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_node_proto_node_proto_init() }
func file_grpc_node_proto_node_proto_init() {
	if File_grpc_node_proto_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_node_proto_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForceLogoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_node_proto_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForceLogoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_node_proto_node_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_node_proto_node_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_node_proto_node_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageRequest_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_node_proto_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_node_proto_node_proto_goTypes,
		DependencyIndexes: file_grpc_node_proto_node_proto_depIdxs,
		MessageInfos:      file_grpc_node_proto_node_proto_msgTypes,
	}.Build()
	File_grpc_node_proto_node_proto = out.File
	file_grpc_node_proto_node_proto_rawDesc = nil
	file_grpc_node_proto_node_proto_goTypes = nil
	file_grpc_node_proto_node_proto_depIdxs = nil
}
